
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wuryan Leonarlie
 */
public class TokoBaju extends javax.swing.JFrame {

    /**
     * Creates new form TokoBaju
     */
    public TokoBaju() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jlTema = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CbH = new javax.swing.JComboBox();
        CbT = new javax.swing.JComboBox();
        CbJ = new javax.swing.JComboBox();
        Jmlh = new javax.swing.JLabel();
        Htotal = new javax.swing.JLabel();
        txtH = new javax.swing.JTextField();
        Total = new javax.swing.JTextField();
        Bpesan = new javax.swing.JButton();
        Bexit = new javax.swing.JButton();
        Bhitung = new javax.swing.JButton();
        txtT = new javax.swing.JTextField();
        txtJ = new javax.swing.JTextField();
        jumlah1 = new javax.swing.JTextField();
        jumlah2 = new javax.swing.JTextField();
        jumlah3 = new javax.swing.JTextField();
        Size = new javax.swing.JLabel();
        SHM = new javax.swing.JRadioButton();
        SHL = new javax.swing.JRadioButton();
        SHXL = new javax.swing.JRadioButton();
        STM = new javax.swing.JRadioButton();
        STL = new javax.swing.JRadioButton();
        STXL = new javax.swing.JRadioButton();
        SJM = new javax.swing.JRadioButton();
        SJL = new javax.swing.JRadioButton();
        SJXL = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlTema.setFont(new java.awt.Font("Kozuka Gothic Pr6N B", 0, 24)); // NOI18N
        jlTema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTema.setText("Toko Baju ZZ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlTema, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlTema, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CbH.setForeground(new java.awt.Color(51, 51, 255));
        CbH.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--HOODIE--", "Aye & Co", "United Heart", "Thanksinsomnia" }));
        CbH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbHActionPerformed(evt);
            }
        });

        CbT.setForeground(new java.awt.Color(0, 0, 255));
        CbT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--T-Shirt--", "Dreambirds Artwear", "Peter Says Denim", "Oxyprey" }));
        CbT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbTActionPerformed(evt);
            }
        });

        CbJ.setForeground(new java.awt.Color(0, 0, 204));
        CbJ.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--JAKET JEANS--", "Levi's", "Samurai", "Dior Homme" }));
        CbJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbJActionPerformed(evt);
            }
        });

        Jmlh.setText("Jumlah");

        Htotal.setText("Harga Total");

        txtH.setText("0");
        txtH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHActionPerformed(evt);
            }
        });

        Total.setText("0");
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });

        Bpesan.setText("PESAN");
        Bpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpesanActionPerformed(evt);
            }
        });

        Bexit.setForeground(new java.awt.Color(255, 0, 0));
        Bexit.setText("EXIT");
        Bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BexitActionPerformed(evt);
            }
        });

        Bhitung.setText("HITUNG");
        Bhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BhitungActionPerformed(evt);
            }
        });

        txtT.setText("0");
        txtT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTActionPerformed(evt);
            }
        });

        txtJ.setText("0");
        txtJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJActionPerformed(evt);
            }
        });

        jumlah1.setText("0");
        jumlah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah1ActionPerformed(evt);
            }
        });

        jumlah2.setText("0");
        jumlah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah2ActionPerformed(evt);
            }
        });

        jumlah3.setText("0");

        Size.setText("Size");

        buttonGroup1.add(SHM);
        SHM.setText("M");

        buttonGroup1.add(SHL);
        SHL.setText("L");

        buttonGroup1.add(SHXL);
        SHXL.setText("XL");

        buttonGroup2.add(STM);
        STM.setText("M");

        buttonGroup2.add(STL);
        STL.setText("L");

        buttonGroup2.add(STXL);
        STXL.setText("XL");

        buttonGroup3.add(SJM);
        SJM.setText("M");

        buttonGroup3.add(SJL);
        SJL.setText("L");

        buttonGroup3.add(SJXL);
        SJXL.setText("XL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jmlh, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Size, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Htotal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(Bhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bpesan, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CbH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CbT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jumlah2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(STM)
                                    .addComponent(STL)
                                    .addComponent(STXL)))
                            .addComponent(SHM)
                            .addComponent(SHL)
                            .addComponent(SHXL))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CbJ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlah3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bexit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SJM)
                            .addComponent(SJL)
                            .addComponent(SJXL))))
                .addGap(92, 92, 92))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jmlh, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlah1)
                    .addComponent(jumlah2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlah3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Size)
                    .addComponent(SHM)
                    .addComponent(STM)
                    .addComponent(SJM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SHL)
                    .addComponent(STL)
                    .addComponent(SJL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SHXL)
                            .addComponent(STXL))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(SJXL)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Htotal)
                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bpesan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(Bexit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbJActionPerformed
        // TODO add your handling code here:
         int harga;
        if (CbJ.getSelectedItem().equals("Jaket Jeans")){
        
    }
        else if (CbJ.getSelectedItem().equals ("Levi's")){
            txtJ.setText("200000");
        }
        else if (CbJ.getSelectedItem().equals ("Samurai")){
            txtJ.setText("185000");}
            else if (CbJ.getSelectedItem().equals ("Dior Homme")){
            txtJ.setText("170000");
            }
    }//GEN-LAST:event_CbJActionPerformed

    private void BpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpesanActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(null, "Terimakasih pesanan anda telah kami proses","Selesai", JOptionPane.OK_OPTION);
        if (answer==JOptionPane.OK_OPTION);
    }//GEN-LAST:event_BpesanActionPerformed

    private void CbHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbHActionPerformed
        // TODO add your handling code here:
        int harga;
        if (CbH.getSelectedItem().equals("--HOODIE--")){
        
    }
        else if (CbH.getSelectedItem().equals ("Aye & Co")){
            txtH.setText("100000");
        }
        else if (CbH.getSelectedItem().equals ("United Heart")){
            txtH.setText("135000");}
        else if (CbH.getSelectedItem().equals ("Thanksinsomnia")){
            txtH.setText("150000");
            }
        
    }//GEN-LAST:event_CbHActionPerformed
        
            
    private void CbTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbTActionPerformed
        // TODO add your handling code here:
          int harga;
        if (CbT.getSelectedItem().equals("T-Shirt")){
        
    }
        else if (CbT.getSelectedItem().equals ("Dreambirds Artwear")){
            txtT.setText("70000");
        }
        else if (CbT.getSelectedItem().equals ("Peter Says Denim")){
            txtT.setText("125000");}
            else if (CbT.getSelectedItem().equals ("Oxyprey")){
            txtT.setText("85000");
            }
    }//GEN-LAST:event_CbTActionPerformed

    private void txtHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHActionPerformed

    private void txtTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTActionPerformed

    private void jumlah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah1ActionPerformed

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TotalActionPerformed

    private void jumlah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah2ActionPerformed

    private void BhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BhitungActionPerformed
        // TODO add your handling code here:
        int harga1,harga2,harga3,jumlahBeli1,jumlahBeli2,jumlahBeli3,Subtotal;
        harga1 = Integer.parseInt(txtH.getText());
        harga2 = Integer.parseInt(txtT.getText());
        harga3 = Integer.parseInt(txtJ.getText());
        jumlahBeli1 = Integer.parseInt(jumlah1.getText());
        jumlahBeli2 = Integer.parseInt(jumlah2.getText());
        jumlahBeli3 = Integer.parseInt(jumlah3.getText());
        Subtotal = harga1 * jumlahBeli1 + harga2 *jumlahBeli2 + harga3 * jumlahBeli3;
           Total.setText("Rp."+Subtotal);
    }//GEN-LAST:event_BhitungActionPerformed

    private void BexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BexitActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(null, "Terima Kasih Atas Kunjungan Anda","Selesai", JOptionPane.OK_OPTION);
        System.exit(answer);
    }//GEN-LAST:event_BexitActionPerformed

    private void txtJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TokoBaju.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TokoBaju.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TokoBaju.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TokoBaju.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TokoBaju().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bexit;
    private javax.swing.JButton Bhitung;
    private javax.swing.JButton Bpesan;
    private javax.swing.JComboBox CbH;
    private javax.swing.JComboBox CbJ;
    private javax.swing.JComboBox CbT;
    private javax.swing.JLabel Htotal;
    private javax.swing.JLabel Jmlh;
    private javax.swing.JRadioButton SHL;
    private javax.swing.JRadioButton SHM;
    private javax.swing.JRadioButton SHXL;
    private javax.swing.JRadioButton SJL;
    private javax.swing.JRadioButton SJM;
    private javax.swing.JRadioButton SJXL;
    private javax.swing.JRadioButton STL;
    private javax.swing.JRadioButton STM;
    private javax.swing.JRadioButton STXL;
    private javax.swing.JLabel Size;
    private javax.swing.JTextField Total;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlTema;
    private javax.swing.JTextField jumlah1;
    private javax.swing.JTextField jumlah2;
    private javax.swing.JTextField jumlah3;
    private javax.swing.JTextField txtH;
    private javax.swing.JTextField txtJ;
    private javax.swing.JTextField txtT;
    // End of variables declaration//GEN-END:variables
}
